# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  default

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    aadSqlPassword: 
    aadSqlUsername: 

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'YourSonarQubeConnection' # Service connection to SonarQube
    scannerMode: 'CLI' # Or 'MSBuild' if using .NET projects
    configMode: 'manual'
    projectKey: 'your-project-key'
    projectName: 'your-project-name'
    projectVersion: '1.0'
    extraProperties: |
      sonar.exclusions=**/*.test.cs
- task: SonarQubeAnalyze
- task: SonarQubePublish