# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  default

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ping "http://20.41.249.208:9000" 5
