trigger:
- main  # Trigger on changes to the main branch

stages:
- stage: QueryAndDeploy
  displayName: Query and Deploy to AKS
  jobs:
  - job: QueryAndDeployJob
    displayName: Interact with AKS
    pool:
      default

    steps:
    # 1. Install kubectl (if not pre-installed)
    - task: KubectlInstaller@0
      displayName: Install kubectl
      inputs:
        kubectlVersion: 'latest'

    # 2. Configure kubectl to use the Kubernetes Service Connection
    - task: Kubernetes@1
      displayName: Set Kubernetes context
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'aks-service-connection'

    # 3. Query AKS for running pods in a namespace
    - script: |
        echo "Querying for running pods in the namespace 'default'..."
        kubectl get pods -n spc-ns
      displayName: Query Running Pods
